name: LuaRocks Release
on:
  pull_request:
  workflow_dispatch:
jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7.2.0
        with:
          version: "1.1.0"
          license: "MIT"
          detailed_description: |
            LuaCATS-like Lua Language Server type annotations for your WezTerm config.
          labels: |
            metalua
            neovim
          copy_directories: |
            {{ neovim.plugin.dirs }}
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
