name: Stylua
on:
  push:
    paths:
      - lua/wezterm/types/*.lua
      - lua/wezterm/types/enum/*.lua
      - lua/wezterm/types/events/*.lua
      - lua/wezterm/types/objects/*.lua
      - lua/wezterm/types/wezterm/*.lua
      - .github/workflows/stylua.yml
  pull_request:
    types:
      - opened
    paths:
      - lua/wezterm/types/*.lua
      - lua/wezterm/types/enum/*.lua
      - lua/wezterm/types/events/*.lua
      - lua/wezterm/types/objects/*.lua
      - lua/wezterm/types/wezterm/*.lua
      - .github/workflows/stylua.yml
jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run stylua
        uses: JohnnyMorganz/stylua-action@v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua
